server:
  port: 8001

spring:
  application:
    name: java-base-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sa2ijdr7xp1n.us-east-3.psdb.cloud:3306
    username: zddmlxiqzk2c
    password: pscale_pw_zYowg5PdaYYUfQat2okvCEb-7MGucBdacAbGIkAk3Tw

mybatis:
  mapperLocations: classpath:/mapper/*.xml
  type-aliases-package: com/dingqing/entity