server:
  port: 8001

spring:
  application:
    name: java-base-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1oo27t8762xhlob0o.mysql.rds.aliyuncs.com:3306/dream_pace?characterEncoding=utf-8
    username: lab_1381998198
    password: f73fd3abd770_#@Aa

mybatis:
  mapperLocations: classpath:/mapper/*.xml
  type-aliases-package: com/dingqing/entity